# 单引号代替双引号
singleQuote: true

# 语句末尾不加分号
semi: false

# 换行宽度（超过该长度自动换行）
printWidth: 80

# 缩进空格数
tabWidth: 2

# 不使用 Tab 缩进
useTabs: false

# 对象/数组末尾是否加逗号
trailingComma: 'es5' # 可选值：none|es5|all

# 箭头函数参数是否加括号（单个参数时）
arrowParens: 'avoid' # 可选值：avoid|always

# HTML 中换行符的处理
htmlWhitespaceSensitivity: 'ignore'

# Vue 单文件组件中 script 和 style 标签内的缩进
vueIndentScriptAndStyle: true

# 换行符格式（lf|crlf|cr|auto）
endOfLine: 'lf'

# 忽略指定文件/目录（需要配合 .prettierignore 文件）
# 注意：ignore 配置在 YAML 中需用数组格式
ignore:
  - 'dist/**/*'
  - 'node_modules/**/*'
